-- AlterTable
ALTER TABLE "categories" ADD COLUMN     "created_at" TIMESTAMP(4) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updated_at" TIMESTAMP(4) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "comments" ADD COLUMN     "created_at" TIMESTAMP(4) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updated_at" TIMESTAMP(4) NOT NULL DEFAULT CURRENT_TIMESTAMP;
